In [1]:
import tensorflow as tf
import numpy as np

sess = tf.InteractiveSession()
np.set_printoptions(precision=2)
np.set_printoptions(suppress=True)

In [2]:
logits = tf.constant([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], tf.float32)
relu = tf.nn.relu(logits)

print(relu.eval())

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]]


In [3]:
a = tf.constant([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], tf.float32)
dropout = tf.nn.dropout(a, keep_prob=0.5)

d = dropout.eval()
print(d)
print(tf.reduce_sum(d, 1, keep_dims=True).eval())
print(tf.count_nonzero(d, 1, keep_dims=True).eval())

[[  2.   4.   6.   0.   0.   0.  14.   0.   0.   0.]
 [  2.   0.   6.   8.  10.  12.  14.   0.   0.   0.]
 [  0.   0.   0.   8.   0.  12.   0.  16.   0.   0.]]
[[ 26.]
 [ 52.]
 [ 36.]]
[[4]
 [6]
 [3]]


In [4]:
a = tf.constant([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], tf.float32)
dropout = tf.nn.dropout(a, keep_prob=0.7)

d = dropout.eval()
print(d)
print(tf.reduce_sum(d, 1, keep_dims=True).eval())
print(tf.count_nonzero(d, 1, keep_dims=True).eval())

[[  1.43   2.86   4.29   5.71   7.14   8.57   0.     0.    12.86  14.29]
 [  1.43   2.86   4.29   0.     7.14   8.57  10.     0.    12.86  14.29]
 [  1.43   2.86   4.29   0.     7.14   8.57   0.     0.     0.    14.29]]
[[ 57.14]
 [ 61.43]
 [ 38.57]]
[[8]
 [8]
 [6]]


In [5]:
keep_prob = tf.placeholder_with_default(1., [])

a = tf.constant([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                 [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], tf.float32)
dropout = tf.nn.dropout(a, keep_prob=keep_prob)

d = dropout.eval()
print(d)
print(tf.reduce_sum(d, 1, keep_dims=True).eval())
print(tf.count_nonzero(d, 1, keep_dims=True).eval())

# d = dropout.eval({keep_prob: 0.5})
# print(d)
# print(tf.reduce_sum(d, 1, keep_dims=True).eval())
# print(tf.count_nonzero(d, 1, keep_dims=True).eval())

[[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]]
[[ 55.]
 [ 55.]
 [ 55.]]
[[10]
 [10]
 [10]]


In [6]:
keep_prob = tf.placeholder_with_default(1., [])

WX_b = tf.constant([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]], tf.float32)

L1 = tf.nn.dropout(tf.nn.relu(WX_b), keep_prob=keep_prob)
L2 = tf.nn.dropout(tf.nn.relu(L1), keep_prob=keep_prob)
L3 = tf.nn.dropout(tf.nn.relu(L2), keep_prob=keep_prob)
L4 = tf.nn.dropout(tf.nn.relu(L3), keep_prob=keep_prob)

# logits = tf.matmul(L4, W5) + b

l1, l2, l3, l4 = sess.run([L1, L2, L3, L4])
print(tf.count_nonzero(tf.concat([l1, l2, l3, l4], 0), 1, keep_dims=True).eval())

# l1, l2, l3, l4 = sess.run([L1, L2, L3, L4], {keep_prob: 0.75})
# print(tf.count_nonzero(tf.concat([l1, l2, l3, l4], 0), 1, keep_dims=True).eval())

[[10]
 [10]
 [10]
 [10]]
