In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# 1) sess = tf.Session()

a = tf.constant(1)

sess = tf.Session()

print(sess.run(a))
# print(a.eval()) # error

sess.close()

# print(sess.run(a)) # error

1


In [3]:
# 2) with tf.Session() as sess:

a = tf.constant(1)

with tf.Session() as sess:
    print(sess.run(a))
    print(a.eval())

1
1


In [4]:
# (3) tf.InteractiveSession()

sess = tf.InteractiveSession()

print(sess.run(a))
print(a.eval())

1
1


In [5]:
xy = np.array([[100, 105, 95, 20000, 101],
               [101, 106, 95, 20010, 102],
               [102, 107, 95, 20020, 103],
               [103, 108, 95, 20030, 104],
               [104, 109, 95, 20040, 105],
               [105, 110, 95, 20050, 106],
               [106, 111, 95, 20060, 107],
               [107, 112, 95, 20070, 108],
               [108, 113, 95, 20080, 109],
               [109, 114, 95, 20090, 110],
               [110, 115, 95, 20100, 111]])
print(xy.shape)

(11, 5)


In [6]:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html
# numpy.hstack(tup)

xy = np.array([[100, 105, 95, 20000, 101],
               [101, 106, 95, 20010, 102],
               [102, 107, 95, 20020, 103],
               [103, 108, 95, 20030, 104],
               [104, 109, 95, 20040, 105],
               [105, 110, 95, 20050, 106],
               [106, 111, 95, 20060, 107],
               [107, 112, 95, 20070, 108],
               [108, 113, 95, 20080, 109],
               [109, 114, 95, 20090, 110],
               [110, 115, 95, 20100, 111]])
x_train = xy[:8]
y_train = xy[1:8+1, [-1]]
print(x_train.shape)
print(y_train.shape)
print(np.hstack((x_train, y_train)))

(8, 5)
(8, 1)
[[  100   105    95 20000   101   102]
 [  101   106    95 20010   102   103]
 [  102   107    95 20020   103   104]
 [  103   108    95 20030   104   105]
 [  104   109    95 20040   105   106]
 [  105   110    95 20050   106   107]
 [  106   111    95 20060   107   108]
 [  107   112    95 20070   108   109]]


In [7]:
xy = np.array([[100, 105, 95, 20000, 101],
               [101, 106, 95, 20010, 102],
               [102, 107, 95, 20020, 103],
               [103, 108, 95, 20030, 104],
               [104, 109, 95, 20040, 105],
               [105, 110, 95, 20050, 106],
               [106, 111, 95, 20060, 107],
               [107, 112, 95, 20070, 108],
               [108, 113, 95, 20080, 109],
               [109, 114, 95, 20090, 110],
               [110, 115, 95, 20100, 111]])
x_test = xy[8:-1]
y_test = xy[8+1:, [-1]]
print(x_test.shape)
print(y_test.shape)
print(np.hstack((x_test, y_test)))

(2, 5)
(2, 1)
[[  108   113    95 20080   109   110]
 [  109   114    95 20090   110   111]]


In [8]:
xy = np.loadtxt('../../dataset/02-stock_google.csv', delimiter=',')
print(xy.shape)

# print(xy.shape[0])
# print(xy.shape[1])

(1257, 5)


In [9]:
train_ratio = 0.8
train_size = int((xy.shape[0]-1) * train_ratio)

print(train_size)

1004


In [10]:
x_train, y_train = xy[:train_size], xy[1:train_size+1, [-1]]
x_test, y_test = xy[train_size:-1], xy[train_size+1:, [-1]]

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(1004, 5) (1004, 1)
(252, 5) (252, 1)


In [11]:
num_features = x_train.shape[1]

print(num_features)

5


In [12]:
# prediction by today's close price

prediction = x_test[:, [-1]]
Y = y_test

abs_diff = tf.abs(prediction - Y)

tf.reduce_mean(abs_diff).eval()

6.0126972539682546

In [13]:
mae, min_diff, max_diff =  tf.reduce_mean(abs_diff), tf.reduce_min(abs_diff), tf.reduce_max(abs_diff)

print('MAE:', mae.eval())
print('MinDiff:', min_diff.eval())
print('MaxDiff:', max_diff.eval())

MAE: 6.01269725397
MinDiff: 0.019958
MaxDiff: 33.579956
