In [15]:
import tensorflow as tf
import numpy as np

sess = tf.InteractiveSession()

In [16]:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html
# numpy.mean(a,
#            axis=None,
#            dtype=None,
#            out=None,
#            keepdims=<class numpy._globals._NoValue>
# )

train_data = np.array([[100, 105, 95, 20000, 101, 102],
                       [101, 106, 95, 20010, 102, 103],
                       [102, 107, 95, 20020, 103, 104],
                       [103, 108, 95, 20030, 104, 105],
                       [104, 109, 95, 20040, 105, 106],
                       [105, 110, 95, 20050, 106, 107],
                       [106, 111, 95, 20060, 107, 108],
                       [107, 112, 95, 20070, 108, 109]])

print(np.mean(train_data))
print(np.mean(train_data).shape)

3425.33333333
()


In [17]:
train_data = np.array([[100, 105, 95, 20000, 101, 102],
                       [101, 106, 95, 20010, 102, 103],
                       [102, 107, 95, 20020, 103, 104],
                       [103, 108, 95, 20030, 104, 105],
                       [104, 109, 95, 20040, 105, 106],
                       [105, 110, 95, 20050, 106, 107],
                       [106, 111, 95, 20060, 107, 108],
                       [107, 112, 95, 20070, 108, 109]])

print(np.mean(train_data, 0))
print(np.mean(train_data, 0).shape)

[   103.5    108.5     95.   20035.     104.5    105.5]
(6,)


In [18]:
train_data = np.array([[100, 105, 95, 20000, 101, 102],
                       [101, 106, 95, 20010, 102, 103],
                       [102, 107, 95, 20020, 103, 104],
                       [103, 108, 95, 20030, 104, 105],
                       [104, 109, 95, 20040, 105, 106],
                       [105, 110, 95, 20050, 106, 107],
                       [106, 111, 95, 20060, 107, 108],
                       [107, 112, 95, 20070, 108, 109]])

print(np.mean(train_data, 1))
print(np.mean(train_data, 1).shape)

[ 3417.16666667  3419.5         3421.83333333  3424.16666667  3426.5
  3428.83333333  3431.16666667  3433.5       ]
(8,)


In [19]:
train_data = np.array([[100, 105, 95, 20000, 101, 102],
                       [101, 106, 95, 20010, 102, 103],
                       [102, 107, 95, 20020, 103, 104],
                       [103, 108, 95, 20030, 104, 105],
                       [104, 109, 95, 20040, 105, 106],
                       [105, 110, 95, 20050, 106, 107],
                       [106, 111, 95, 20060, 107, 108],
                       [107, 112, 95, 20070, 108, 109]])

print(tf.reduce_mean(train_data).eval())
print(tf.reduce_mean(train_data, 0).eval())
print(tf.reduce_mean(train_data, 1).eval())

3425
[  103   108    95 20035   104   105]
[3417 3419 3421 3424 3426 3428 3431 3433]


In [20]:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html
# numpy.std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=<class numpy._globals._NoValue>)

train_data = np.array([[100, 105, 95, 20000, 101, 102],
                       [101, 106, 95, 20010, 102, 103],
                       [102, 107, 95, 20020, 103, 104],
                       [103, 108, 95, 20030, 104, 105],
                       [104, 109, 95, 20040, 105, 106],
                       [105, 110, 95, 20050, 106, 107],
                       [106, 111, 95, 20060, 107, 108],
                       [107, 112, 95, 20070, 108, 109]])

print(np.std(train_data))

7428.07602202


In [21]:
train_data = np.array([[100, 105, 95, 20000, 101, 102],
                       [101, 106, 95, 20010, 102, 103],
                       [102, 107, 95, 20020, 103, 104],
                       [103, 108, 95, 20030, 104, 105],
                       [104, 109, 95, 20040, 105, 106],
                       [105, 110, 95, 20050, 106, 107],
                       [106, 111, 95, 20060, 107, 108],
                       [107, 112, 95, 20070, 108, 109]])

print(np.std(train_data, 0))
print(np.std(train_data, 0).shape)
print(np.std(train_data, 1))
print(np.std(train_data, 1).shape)

[  2.29128785   2.29128785   0.          22.91287847   2.29128785
   2.29128785]
(6,)
[ 7416.06911638  7419.49788845  7422.92667835  7426.35548607  7429.78431158
  7433.21315486  7436.64201587  7440.0708946 ]
(8,)


In [22]:
train_data = np.array([[100, 105, 95, 20000, 101, 102],
                       [101, 106, 95, 20010, 102, 103],
                       [102, 107, 95, 20020, 103, 104],
                       [103, 108, 95, 20030, 104, 105],
                       [104, 109, 95, 20040, 105, 106],
                       [105, 110, 95, 20050, 106, 107],
                       [106, 111, 95, 20060, 107, 108],
                       [107, 112, 95, 20070, 108, 109]])

mean = np.mean(train_data, 0)
std = np.std(train_data, 0)

norm = (train_data - mean) / std

print(norm)

[[-1.52752523 -1.52752523         nan -1.52752523 -1.52752523 -1.52752523]
 [-1.09108945 -1.09108945         nan -1.09108945 -1.09108945 -1.09108945]
 [-0.65465367 -0.65465367         nan -0.65465367 -0.65465367 -0.65465367]
 [-0.21821789 -0.21821789         nan -0.21821789 -0.21821789 -0.21821789]
 [ 0.21821789  0.21821789         nan  0.21821789  0.21821789  0.21821789]
 [ 0.65465367  0.65465367         nan  0.65465367  0.65465367  0.65465367]
 [ 1.09108945  1.09108945         nan  1.09108945  1.09108945  1.09108945]
 [ 1.52752523  1.52752523         nan  1.52752523  1.52752523  1.52752523]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: RuntimeWarning: invalid value encountered in true_divide
  del sys.path[0]


In [23]:
train_data = np.array([[100, 105, 95, 20000, 101, 102],
                      [101, 106, 95, 20010, 102, 103],
                      [102, 107, 95, 20020, 103, 104],
                      [103, 108, 95, 20030, 104, 105],
                      [104, 109, 95, 20040, 105, 106],
                      [105, 110, 95, 20050, 106, 107],
                      [106, 111, 95, 20060, 107, 108],
                      [107, 112, 95, 20070, 108, 109]])

epsilon = 1e-12
mean = np.mean(train_data, 0)
std = np.std(train_data, 0)

norm = (train_data - mean) / (std + epsilon)

print(norm)

[[-1.52752523 -1.52752523  0.         -1.52752523 -1.52752523 -1.52752523]
 [-1.09108945 -1.09108945  0.         -1.09108945 -1.09108945 -1.09108945]
 [-0.65465367 -0.65465367  0.         -0.65465367 -0.65465367 -0.65465367]
 [-0.21821789 -0.21821789  0.         -0.21821789 -0.21821789 -0.21821789]
 [ 0.21821789  0.21821789  0.          0.21821789  0.21821789  0.21821789]
 [ 0.65465367  0.65465367  0.          0.65465367  0.65465367  0.65465367]
 [ 1.09108945  1.09108945  0.          1.09108945  1.09108945  1.09108945]
 [ 1.52752523  1.52752523  0.          1.52752523  1.52752523  1.52752523]]


In [24]:
a = np.array([[1, 2, 3],
              [5, 6, 7],
              [9, 10, 11],
              [13, 14, 15]])
b = np.array([[4],
              [8],
              [12],
              [16]])
print(np.hstack((a, b)))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [25]:
train_data = np.array([[100, 105, 95, 20000, 101, 102],
                       [101, 106, 95, 20010, 102, 103],
                       [102, 107, 95, 20020, 103, 104],
                       [103, 108, 95, 20030, 104, 105],
                       [104, 109, 95, 20040, 105, 106],
                       [105, 110, 95, 20050, 106, 107],
                       [106, 111, 95, 20060, 107, 108],
                       [107, 112, 95, 20070, 108, 109]])

num_features = 5
x_train = train_data[:, :-1]

X = tf.placeholder(tf.float32, [None, num_features])

W = tf.Variable(tf.random_normal([num_features, 1]))
b = tf.Variable(tf.random_normal([1]))

H = tf.matmul(X, W) + b

sess.run(tf.global_variables_initializer())

print(H.eval({X: x_train}))

[[-28801.92382812]
 [-28816.41015625]
 [-28830.8984375 ]
 [-28845.3828125 ]
 [-28859.86914062]
 [-28874.35742188]
 [-28888.84375   ]
 [-28903.33007812]]


In [34]:
train_data = np.array([[100, 105, 95, 20000, 101, 102],
                       [101, 106, 95, 20010, 102, 103],
                       [102, 107, 95, 20020, 103, 104],
                       [103, 108, 95, 20030, 104, 105],
                       [104, 109, 95, 20040, 105, 106],
                       [105, 110, 95, 20050, 106, 107],
                       [106, 111, 95, 20060, 107, 108],
                       [107, 112, 95, 20070, 108, 109]])

learning_rate = 0.1
num_features = 5
epsilon = 1e-12
x_train = train_data[:, :-1]
y_train = train_data[:, [-1]]

train_data = np.hstack((x_train, y_train))
mean = np.mean(train_data, axis=0)
std = np.std(train_data, axis=0)

X = tf.placeholder(tf.float32, [None, num_features])
Y = tf.placeholder(tf.float32, [None, 1])
M = tf.placeholder(tf.float32, [num_features+1])
S = tf.placeholder(tf.float32, [num_features+1])

W = tf.Variable(tf.random_normal([num_features, 1]))
b = tf.Variable(tf.random_normal([1]))

X_mean, Y_mean = M[:num_features], M[num_features:]
X_std, Y_std = S[:num_features], S[num_features:]

X_norm = (X - X_mean) / (X_std + epsilon)
Y_norm = (Y - Y_mean) / (Y_std + epsilon)

H_norm = tf.matmul(X_norm, W) + b

cost = tf.reduce_mean(tf.square(H_norm - Y_norm))

train = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

prediction = H_norm * (Y_std + epsilon) + Y_mean

abs_diff = tf.abs(prediction - Y)
mae, min_diff, max_diff =  tf.reduce_mean(abs_diff), tf.reduce_min(abs_diff), tf.reduce_max(abs_diff)

sess.run(tf.global_variables_initializer())

print(H_norm.eval({X: x_train, M: mean, S: std}))
print(cost.eval({X: x_train, Y: y_train, M: mean, S: std}))
print(prediction.eval({X: x_train, Y: y_train, M: mean, S: std}))
print(sess.run([mae, min_diff, max_diff], {X: x_train, Y: y_train, M: mean, S: std}))

[[ 3.72428846]
 [ 3.08144522]
 [ 2.43860173]
 [ 1.79575825]
 [ 1.152915  ]
 [ 0.51007146]
 [-0.13277197]
 [-0.77561522]]
8.2891
[[ 114.03341675]
 [ 112.56047821]
 [ 111.08753967]
 [ 109.61460114]
 [ 108.1416626 ]
 [ 106.66872406]
 [ 105.19577789]
 [ 103.72283936]]
[5.4812946, 0.33127594, 12.033417]


In [30]:
train_data = np.array([[100, 105, 95, 20000, 101, 102],
                       [101, 106, 95, 20010, 102, 103],
                       [102, 107, 95, 20020, 103, 104],
                       [103, 108, 95, 20030, 104, 105],
                       [104, 109, 95, 20040, 105, 106],
                       [105, 110, 95, 20050, 106, 107],
                       [106, 111, 95, 20060, 107, 108],
                       [107, 112, 95, 20070, 108, 109]])

num_features = 5
epsilon = 1e-12
x_train = train_data[:, :-1]
y_train = train_data[:, [-1]]

x_mean = np.mean(x_train, 0)
x_std = np.std(x_train, 0)
y_mean = np.mean(y_train, 0)
y_std = np.std(y_train, 0)

X = tf.placeholder(tf.float32, [None, num_features])
Y = tf.placeholder(tf.float32, [None, 1])

W = tf.Variable(tf.random_normal([num_features, 1]))
b = tf.Variable(tf.random_normal([1]))

X_mean = tf.placeholder(tf.float32, [num_features])
X_std = tf.placeholder(tf.float32, [num_features])
Y_mean = tf.placeholder(tf.float32, [1])
Y_std = tf.placeholder(tf.float32, [1])

X_norm = (X - X_mean) / (X_std + epsilon)
Y_norm = (Y - Y_mean) / (Y_std + epsilon)

H_norm = tf.matmul(X_norm, W) + b

cost = tf.reduce_mean(tf.square(H_norm - Y_norm)) # Y

train = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost)

prediction = H_norm * (Y_std + epsilon) + Y_mean

abs_diff = tf.abs(prediction - Y)
mae, min_diff, max_diff =  tf.reduce_mean(abs_diff), tf.reduce_min(abs_diff), tf.reduce_max(abs_diff)

sess.run(tf.global_variables_initializer())

print(H_norm.eval({X: x_train, X_mean: x_mean, X_std: x_std}))
print(cost.eval({X: x_train, Y: y_train, X_mean: x_mean, X_std: x_std, Y_mean: y_mean, Y_std: y_std}))
print(prediction.eval({X: x_train, Y: y_train, X_mean: x_mean, X_std: x_std, Y_mean: y_mean, Y_std: y_std}))
print(sess.run([mae, min_diff, max_diff], {X: x_train, Y: y_train, X_mean: x_mean, X_std: x_std, Y_mean: y_mean, Y_std: y_std}))

[[ 0.87648225]
 [ 0.20914376]
 [-0.45819497]
 [-1.12553346]
 [-1.79287207]
 [-2.46021056]
 [-3.12754917]
 [-3.79488778]]
8.52544
[[ 107.50827026]
 [ 105.9792099 ]
 [ 104.45014191]
 [ 102.92108154]
 [ 101.39201355]
 [  99.86294556]
 [  98.33388519]
 [  96.8048172 ]]
[5.5778599, 0.45014191, 12.195183]
