In [1]:
import tensorflow as tf

tf.set_random_seed(0)

sess = tf.InteractiveSession()

In [2]:
logits = tf.constant([[10, 2, 3],
                      [2, 4, -2],
                      [-2, 3, 8]], tf.float32)

H = tf.nn.sigmoid(logits)

print(H.eval())

[[ 0.99995458  0.88079703  0.95257413]
 [ 0.88079703  0.98201376  0.11920292]
 [ 0.11920292  0.95257413  0.99966466]]


In [3]:
# https://www.tensorflow.org/api_docs/python/tf/nn/relu
# tf.relu(
#     features,
#     name=None
# )
logits = tf.constant([[10, 2, 3],
                      [2, 4, -2],
                      [-2, 3, 8]], tf.float32)

H = tf.nn.relu(logits)

print(H.eval())

[[ 10.   2.   3.]
 [  2.   4.   0.]
 [  0.   3.   8.]]


In [4]:
logits = tf.constant([[10, 2, 3],
                      [2, 4, -2],
                      [-2, 3, 8]], tf.float32)
print(tf.maximum(logits, 0).eval())

[[ 10.   2.   3.]
 [  2.   4.   0.]
 [  0.   3.   8.]]


In [5]:
X = tf.placeholder(tf.float32, [None, 2])

W1 = tf.Variable(tf.random_normal([2, 16]))
W2 = tf.Variable(tf.random_normal([16, 16]))
W3 = tf.Variable(tf.random_normal([16, 16]))
W4 = tf.Variable(tf.random_normal([16, 16]))
W5 = tf.Variable(tf.random_normal([16, 4]))

b1 = tf.Variable(tf.zeros([16]))
b2 = tf.Variable(tf.zeros([16]))
b3 = tf.Variable(tf.zeros([16]))
b4 = tf.Variable(tf.zeros([16]))
b5 = tf.Variable(tf.zeros([4]))

L1 = tf.nn.sigmoid(tf.matmul(X, W1) + b1)
L2 = tf.nn.sigmoid(tf.matmul(L1, W2) + b2)
L3 = tf.nn.sigmoid(tf.matmul(L2, W3) + b3)
L4 = tf.nn.sigmoid(tf.matmul(L3, W4) + b4)

logits = tf.matmul(L4, W5) + b5

sess.run(tf.global_variables_initializer())

print(logits.eval({X: [[1, 2],
                       [3, 4],
                       [5, 6]]}))

print(logits.eval({X: [[1, 2],
                       [3, 4],
                       [50, 60]]}))

[[-1.26291096 -0.46090817  1.4274621  -2.73798013]
 [-1.47733939 -0.36946404  1.31702483 -2.81154442]
 [-1.55446351 -0.31293929  1.25203395 -2.81277347]]
[[-1.26291096 -0.46090817  1.4274621  -2.73798013]
 [-1.47733939 -0.36946404  1.31702483 -2.81154442]
 [-1.59847391 -0.27683979  1.21143734 -2.80545568]]


In [6]:
X = tf.placeholder(tf.float32, [None, 2])

W1 = tf.Variable(tf.random_normal([2, 16]))
W2 = tf.Variable(tf.random_normal([16, 16]))
W3 = tf.Variable(tf.random_normal([16, 16]))
W4 = tf.Variable(tf.random_normal([16, 16]))
W5 = tf.Variable(tf.random_normal([16, 4]))

b1 = tf.Variable(tf.zeros([16]))
b2 = tf.Variable(tf.zeros([16]))
b3 = tf.Variable(tf.zeros([16]))
b4 = tf.Variable(tf.zeros([16]))
b5 = tf.Variable(tf.zeros([4]))

L1 = tf.nn.relu(tf.matmul(X, W1) + b1)
L2 = tf.nn.relu(tf.matmul(L1, W2) + b2)
L3 = tf.nn.relu(tf.matmul(L2, W3) + b3)
L4 = tf.nn.relu(tf.matmul(L3, W4) + b4)

logits = tf.matmul(L4, W5) + b5

sess.run(tf.global_variables_initializer())

print(logits.eval({X: [[1, 2],
                       [3, 4],
                       [5, 6]]}))

print(logits.eval({X: [[1, 2],
                       [3, 4],
                       [50, 60]]}))

[[ 189.10604858  123.17449951   96.80147552  144.17573547]
 [ 553.32946777  252.91471863  217.99275208  376.28585815]
 [ 917.88757324  389.08676147  330.90988159  622.58703613]]
[[  189.10604858   123.17449951    96.80147552   144.17573547]
 [  553.32946777   252.91471863   217.99275208   376.28585815]
 [ 9178.87597656  3890.86791992  3309.10058594  6225.87255859]]
