In [1]:
import tensorflow as tf

tf.set_random_seed(0)

sess = tf.InteractiveSession()

In [2]:
# https://www.tensorflow.org/programmers_guide/variables
# https://www.tensorflow.org/api_docs/python/tf/get_variable
# get_variable(
#     name,
#     shape=None,
#     dtype=None,
#     initializer=None,
#     regularizer=None,
#     trainable=True,
#     collections=None,
#     caching_device=None,
#     partitioner=None,
#     validate_shape=True,
#     use_resource=None,
#     custom_getter=None
# )

W = tf.get_variable('W', [4, 3])
b = tf.get_variable('b', [3])

sess.run(tf.global_variables_initializer())

print(W.eval())
print(b.eval())


[[-0.33211005  0.3556993   0.4483602 ]
 [ 0.68384182  0.85159254  0.80803454]
 [-0.02246642 -0.21761572  0.11428106]
 [ 0.91304648  0.24815297  0.20206892]]
[ 0.10906506  0.71418476  0.11083865]


In [3]:
W2 = tf.get_variable('W2', [4, 3], initializer=tf.random_normal_initializer())
b2 = tf.get_variable('b2', [3], initializer=tf.zeros_initializer())

sess.run(tf.global_variables_initializer())

print(W2.eval())
print(b2.eval())

[[ 1.37785816  0.23252471 -0.04414748]
 [-0.92046231  1.23291934 -0.05653581]
 [ 0.97631824 -0.66159475  0.37501836]
 [-0.8942281   0.06148557  0.30448037]]
[ 0.  0.  0.]


In [4]:
logits = tf.constant([[1, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
numerator = tf.exp(logits)

print(logits.eval())
print(numerator.eval())

[[ 1.   0.5 -1. ]
 [ 1.   0.5 -1. ]
 [ 2.   0.5 -1. ]
 [-1.  -2.  -3. ]
 [ 4.   2.   1. ]]
[[  2.71828175e+00   1.64872122e+00   3.67879450e-01]
 [  2.71828175e+00   1.64872122e+00   3.67879450e-01]
 [  7.38905621e+00   1.64872122e+00   3.67879450e-01]
 [  3.67879450e-01   1.35335281e-01   4.97870669e-02]
 [  5.45981483e+01   7.38905621e+00   2.71828175e+00]]


In [5]:
logits = tf.constant([[1, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
numerator = tf.exp(logits)
denominator = tf.reduce_sum(tf.exp(logits), 1, keep_dims=True)

print(numerator.eval())
print(denominator.eval())

[[  2.71828175e+00   1.64872122e+00   3.67879450e-01]
 [  2.71828175e+00   1.64872122e+00   3.67879450e-01]
 [  7.38905621e+00   1.64872122e+00   3.67879450e-01]
 [  3.67879450e-01   1.35335281e-01   4.97870669e-02]
 [  5.45981483e+01   7.38905621e+00   2.71828175e+00]]
[[  4.73488235]
 [  4.73488235]
 [  9.40565681]
 [  0.55300176]
 [ 64.70549011]]


In [6]:
logits = tf.constant([[1, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
numerator = tf.exp(logits)
denominator = tf.reduce_sum(tf.exp(logits), 1, keep_dims=True)
H = numerator / denominator

print(numerator.eval())
print(denominator.eval())
print(H.eval())

[[  2.71828175e+00   1.64872122e+00   3.67879450e-01]
 [  2.71828175e+00   1.64872122e+00   3.67879450e-01]
 [  7.38905621e+00   1.64872122e+00   3.67879450e-01]
 [  3.67879450e-01   1.35335281e-01   4.97870669e-02]
 [  5.45981483e+01   7.38905621e+00   2.71828175e+00]]
[[  4.73488235]
 [  4.73488235]
 [  9.40565681]
 [  0.55300176]
 [ 64.70549011]]
[[ 0.57409698  0.34820744  0.07769559]
 [ 0.57409698  0.34820744  0.07769559]
 [ 0.78559703  0.17529039  0.03911258]
 [ 0.665241    0.24472848  0.09003057]
 [ 0.8437947   0.1141952   0.04201007]]


In [7]:
logits = tf.constant([[1, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
H = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), 1, keep_dims=True)

print(H.eval())
print(tf.reduce_sum(H, 1, keep_dims=True).eval())

[[ 0.57409698  0.34820744  0.07769559]
 [ 0.57409698  0.34820744  0.07769559]
 [ 0.78559703  0.17529039  0.03911258]
 [ 0.665241    0.24472848  0.09003057]
 [ 0.8437947   0.1141952   0.04201007]]
[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]


In [8]:
# https://www.tensorflow.org/api_docs/python/tf/argmax
# tf.argmax(
#     input,
#     axis=None,
#     name=None,
#     dimension=None,
#     output_type=tf.int64
# )

logits = tf.constant([[1, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
H = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), 1, keep_dims=True)
prediction = tf.argmax(H, 1)

print(H.eval())
print(prediction.eval())

[[ 0.57409698  0.34820744  0.07769559]
 [ 0.57409698  0.34820744  0.07769559]
 [ 0.78559703  0.17529039  0.03911258]
 [ 0.665241    0.24472848  0.09003057]
 [ 0.8437947   0.1141952   0.04201007]]
[0 0 0 0 0]


In [9]:
logits = tf.constant([[1, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
Y = tf.constant([[1, 0, 0],
                 [1, 0, 0],
                 [1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 1]], tf.float32)
H = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), 1, keep_dims=True)
prediction = tf.argmax(H, 1)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, tf.argmax(Y, 1)), tf.float32))

print(H.eval())
print(prediction.eval())
print(tf.argmax(Y, 1).eval())
print(accuracy.eval())

[[ 0.57409698  0.34820744  0.07769559]
 [ 0.57409698  0.34820744  0.07769559]
 [ 0.78559703  0.17529039  0.03911258]
 [ 0.665241    0.24472848  0.09003057]
 [ 0.8437947   0.1141952   0.04201007]]
[0 0 0 0 0]
[0 0 0 1 2]
0.6


In [10]:
logits = tf.constant([[1, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
Y = tf.constant([[1, 0, 0],
                 [1, 0, 0],
                 [1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 1]], tf.float32)
H = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), 1, keep_dims=True)

print(Y.eval())
print((-tf.log(H)).eval())

[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 0.55495691  1.05495691  2.55495691]
 [ 0.55495691  1.05495691  2.55495691]
 [ 0.24131131  1.74131131  3.24131131]
 [ 0.40760589  1.40760589  2.40760589]
 [ 0.16984606  2.16984606  3.16984606]]


In [11]:
logits = tf.constant([[1, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
Y = tf.constant([[1, 0, 0],
                 [1, 0, 0],
                 [1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 1]], tf.float32)
H = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), 1, keep_dims=True)
c = - Y * tf.log(H)

print(c.eval())

[[ 0.55495691  0.          0.        ]
 [ 0.55495691  0.          0.        ]
 [ 0.24131131  0.          0.        ]
 [ 0.          1.40760589  0.        ]
 [ 0.          0.          3.16984606]]


In [12]:
logits = tf.constant([[1, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
Y = tf.constant([[1, 0, 0],
                 [1, 0, 0],
                 [1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 1]], tf.float32)
H = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), 1, keep_dims=True)
c = tf.reduce_sum(- Y * tf.log(H), 1)

print(c.eval())

[ 0.55495691  0.55495691  0.24131131  1.40760589  3.16984606]


In [13]:
logits = tf.constant([[1, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
Y = tf.constant([[1, 0, 0],
                 [1, 0, 0],
                 [1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 1]], tf.float32)
H = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), 1, keep_dims=True)
cost = -tf.reduce_mean(tf.reduce_sum(Y * tf.log(H), axis=1))

print(cost.eval())

1.18574


In [14]:
logits = tf.constant([[1, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, 0, -3],
                      [1, 2, 4]], tf.float32)
Y = tf.constant([[1, 0, 0],
                 [1, 0, 0],
                 [1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 1]], tf.float32)
H = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), 1, keep_dims=True)
cost = -tf.reduce_mean(tf.reduce_sum(Y * tf.log(H), axis=1))

print(cost.eval())

0.374017
