In [1]:
import tensorflow as tf

sess = tf.InteractiveSession()

In [2]:
logits = tf.constant([[1, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
H = tf.exp(logits) / tf.reduce_sum(tf.exp(logits), 1, keep_dims=True)

print(H.eval())

[[ 0.57409698  0.34820744  0.07769559]
 [ 0.57409698  0.34820744  0.07769559]
 [ 0.78559703  0.17529039  0.03911258]
 [ 0.665241    0.24472848  0.09003057]
 [ 0.8437947   0.1141952   0.04201007]]


In [3]:
logits = tf.constant([[1, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
H = tf.nn.softmax(logits)

print(H.eval())

[[ 0.57409698  0.34820741  0.07769558]
 [ 0.57409698  0.34820741  0.07769558]
 [ 0.78559703  0.17529039  0.03911257]
 [ 0.66524094  0.24472848  0.09003057]
 [ 0.8437947   0.11419519  0.04201007]]


In [4]:
logits = tf.constant([[1, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
Y = tf.constant([[1, 0, 0],
                 [1, 0, 0],
                 [1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 1]], tf.float32)
H = tf.nn.softmax(logits)
cost = -tf.reduce_mean(tf.reduce_sum(Y * tf.log(H), axis=1))

print(H.eval())
print(cost.eval())

[[ 0.57409698  0.34820741  0.07769558]
 [ 0.57409698  0.34820741  0.07769558]
 [ 0.78559703  0.17529039  0.03911257]
 [ 0.66524094  0.24472848  0.09003057]
 [ 0.8437947   0.11419519  0.04201007]]
1.18574


In [5]:
logits = tf.constant([[1, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
Y = tf.constant([[1, 0, 0],
                 [1, 0, 0],
                 [1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 1]], tf.float32)
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=Y, logits=logits))

print(cost.eval())

1.18574


In [6]:
logits = tf.constant([[100, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
Y = tf.constant([[1, 0, 0],
                 [1, 0, 0],
                 [1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 1]], tf.float32)
c = tf.reduce_sum(Y * tf.log(H), axis=1)
print(c.eval())

c = tf.nn.softmax_cross_entropy_with_logits(labels=Y, logits=logits)
print(c.eval())

[-0.55495691 -0.55495691 -0.24131131 -1.40760589 -3.16984606]
[ 0.          0.55495691  0.24131133  1.40760589  3.16984606]


In [7]:
logits = tf.constant([[100, 0.5, -1],
                      [1, 0.5, -1],
                      [2, 0.5, -1],
                      [-1, -2, -3],
                      [4, 2, 1]], tf.float32)
Y = tf.constant([[1, 0, 0],
                 [1, 0, 0],
                 [1, 0, 0],
                 [0, 1, 0],
                 [0, 0, 1]], tf.float32)
H = tf.nn.softmax(logits)

prediction = tf.argmax(H, 1)
print(prediction.eval())

prediction = tf.argmax(logits, 1)
print(prediction.eval())

[0 0 0 0 0]
[0 0 0 0 0]
