In [1]:
import tensorflow as tf

sess = tf.InteractiveSession()

In [2]:
a = tf.constant([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])
print(a.eval())
print(a.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)


In [3]:
a = tf.constant([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])
b = tf.reshape(a, [2, 8])

print(a.shape)
print(b.eval())
print(b.shape)

(4, 4)
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
(2, 8)


In [4]:
a = tf.constant([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])
b = tf.reshape(a, [4, 2, 2])

print(a.shape)
print(b.eval())
print(b.shape)

(4, 4)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]
(4, 2, 2)


In [5]:
a = tf.constant([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [13, 14, 15, 16]])
b = tf.reshape(a, [-1, 2])

print(a.shape)
print(b.eval())
print(b.shape)

(4, 4)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
(8, 2)


In [6]:
a = tf.constant([[[1, 2, 3, 4],
                  [5, 6, 7, 8]],
                 [[9, 10, 11, 12],
                  [13, 14, 15, 16]]])

b = tf.reshape(a, [-1, 4])

print(a.shape)
print(b.eval())
print(b.shape)

(2, 2, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)


In [7]:
Y = tf.constant([[0],
                 [0],
                 [0],
                 [1],
                 [1],
                 [1],
                 [2],
                 [2],
                 [2]], tf.int32)
print(Y.shape)

(9, 1)


In [8]:
Y = tf.constant([[0],
                 [0],
                 [0],
                 [1],
                 [1],
                 [1],
                 [2],
                 [2],
                 [2]], tf.int32)
Y_one_hot = tf.one_hot(Y, 3)

print(Y.shape)
print(Y_one_hot.eval())
print(Y_one_hot.shape)

(9, 1)
[[[ 1.  0.  0.]]

 [[ 1.  0.  0.]]

 [[ 1.  0.  0.]]

 [[ 0.  1.  0.]]

 [[ 0.  1.  0.]]

 [[ 0.  1.  0.]]

 [[ 0.  0.  1.]]

 [[ 0.  0.  1.]]

 [[ 0.  0.  1.]]]
(9, 1, 3)


In [9]:
Y = tf.constant([[0],
                 [0],
                 [0],
                 [1],
                 [1],
                 [1],
                 [2],
                 [2],
                 [2]], tf.int32)
Y_one_hot = tf.reshape(tf.one_hot(Y, 3), [-1, 3])

print(Y.shape)
print(Y_one_hot.eval())
print(Y_one_hot.shape)

(9, 1)
[[ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  1.]]
(9, 3)


In [10]:
logits = tf.constant([[1., .5, .2],
                      [.5, 1., .2],
                      [.2, .5, 1.]], tf.float32)
Y = tf.constant([[0],
                 [1],
                 [2]], tf.int32)
Y_one_hot = tf.reshape(tf.one_hot(Y, 3), [-1, 3])

prediction = tf.argmax(logits, 1)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, tf.argmax(Y_one_hot, 1)), tf.float32))

print(logits.eval())
print(prediction.eval())
print(accuracy.eval())

[[ 1.   0.5  0.2]
 [ 0.5  1.   0.2]
 [ 0.2  0.5  1. ]]
[0 1 2]
1.0
