In [1]:
import tensorflow as tf
import numpy as np

tf.set_random_seed(0)
sess = tf.InteractiveSession()

In [2]:
# https://www.tensorflow.org/api_docs/python/tf/contrib/layers/fully_connected
# tf.fully_connected(
#     inputs,
#     num_outputs,
#     activation_fn=tf.nn.relu,
#     normalizer_fn=None,
#     normalizer_params=None,
#     weights_initializer=initializers.xavier_initializer(),
#     weights_regularizer=None,
#     biases_initializer=tf.zeros_initializer(),
#     biases_regularizer=None,
#     reuse=None,
#     variables_collections=None,
#     outputs_collections=None,
#     trainable=True,
#     scope=None
# )

X = tf.placeholder(tf.float32, [None, 2]) # [None, None] ?

H = tf.contrib.layers.fully_connected(X, 1, None)

sess.run(tf.global_variables_initializer())

print(H.eval({X: [[1, 2],
                  [3, 4],
                  [5, 6]]}))

[[-2.30085135]
 [-5.23155308]
 [-8.16225433]]


In [3]:
X = tf.placeholder(tf.float32, [None, 2])

H = tf.contrib.layers.fully_connected(X, 1, tf.nn.sigmoid)

sess.run(tf.global_variables_initializer())

print(H.eval({X: [[1, 2],
                  [3, 4],
                  [5, 6]]}))

[[ 0.91155583]
 [ 0.98873949]
 [ 0.99866498]]


In [4]:
X = tf.placeholder(tf.float32, [None, 2])

H = tf.contrib.layers.fully_connected(X, 4, None)

sess.run(tf.global_variables_initializer())

print(H.eval({X: [[1, 2],
                  [3, 4],
                  [5, 6]]}))

[[-0.92030478  1.30180979 -1.56053352  1.32262087]
 [-2.42455912  2.20901012 -3.21592522  3.61487865]
 [-3.92881346  3.11621046 -4.87131691  5.90713644]]


In [5]:
X = tf.placeholder(tf.float32, [None, 2])

H = tf.contrib.layers.fully_connected(X, 4, tf.nn.softmax)

sess.run(tf.global_variables_initializer())

print(H.eval({X: [[1, 2],
                  [3, 4],
                  [5, 6]]}))

print(tf.reduce_sum(H, 1).eval({X: [[1, 2],
                                    [3, 4],
                                    [5, 6]]}))

[[ 0.2643609   0.07163715  0.3645592   0.29944277]
 [ 0.30613974  0.00975491  0.47735074  0.20675462]
 [ 0.31550989  0.00118217  0.55626005  0.12704787]]
[ 1.  1.  1.]


In [6]:
# https://www.tensorflow.org/api_docs/python/tf/contrib/layers/fully_connected
# tf.fully_connected(
#     inputs,
#     num_outputs,
#     activation_fn=tf.nn.relu,
#     normalizer_fn=None,
#     normalizer_params=None,
#     weights_initializer=initializers.xavier_initializer(),
#     weights_regularizer=None,
#     biases_initializer=tf.zeros_initializer(),
#     biases_regularizer=None,
#     reuse=None,
#     variables_collections=None,
#     outputs_collections=None,
#     trainable=True,
#     scope=None
# )

X = tf.placeholder(tf.float32, [None, 2])

init_w = tf.ones_initializer()
init_b = tf.zeros_initializer()

logits = tf.contrib.layers.fully_connected(X, 1, None, weights_initializer=init_w, biases_initializer=init_b)

sess.run(tf.global_variables_initializer())

print(logits.eval({X: [[1, 2],
                       [3, 4],
                       [5, 6]]}))

[[  3.]
 [  7.]
 [ 11.]]


In [7]:
X = tf.placeholder(tf.float32, [None, 2])

init_w = tf.random_normal_initializer()
init_b = tf.zeros_initializer()

logits = tf.contrib.layers.fully_connected(X, 10, None, weights_initializer=init_w, biases_initializer=init_b)

sess.run(tf.global_variables_initializer())

print(logits.eval({X: [[1, 2],
                       [3, 4],
                       [5, 6]]}))

[[ -2.44866776  -2.89501238  -2.77342701   4.11356735  -1.00265539
   -4.12412214   2.21305132  -0.59664595   2.31566763  -0.36860311]
 [ -3.98609614  -6.73234367  -6.80894089  10.71028328  -1.66190505
  -10.35792542   5.3970623   -1.93562818   4.83213472  -2.43302846]
 [ -5.52352428 -10.56967354 -10.84445381  17.30699921  -2.32115507
  -16.59172821   8.58107376  -3.27461052   7.34860134  -4.49745321]]
