In [1]:
import tensorflow as tf
from tensorflow.contrib.layers import conv2d, max_pool2d, dropout, fully_connected
from tensorflow.examples.tutorials.mnist import input_data
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

tf.set_random_seed(0)
sess = tf.InteractiveSession()
mnist = input_data.read_data_sets('../../dataset/MNIST_data/', one_hot=True)

np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

Extracting ../../dataset/MNIST_data/train-images-idx3-ubyte.gz
Extracting ../../dataset/MNIST_data/train-labels-idx1-ubyte.gz
Extracting ../../dataset/MNIST_data/t10k-images-idx3-ubyte.gz
Extracting ../../dataset/MNIST_data/t10k-labels-idx1-ubyte.gz


In [2]:
# https://www.tensorflow.org/api_docs/python/tf/contrib/layers/conv2d
# tf.contrib.layers.conv2d(
#     inputs,
#     num_outputs,
#     kernel_size,
#     stride=1,
#     padding='SAME',
#     data_format=None,
#     rate=1,
#     activation_fn=tf.nn.relu,
#     normalizer_fn=None,
#     normalizer_params=None,
#     weights_initializer=initializers.xavier_initializer(),
#     weights_regularizer=None,
#     biases_initializer=tf.zeros_initializer(),
#     biases_regularizer=None,
#     reuse=None,
#     variables_collections=None,
#     outputs_collections=None,
#     trainable=True,
#     scope=None
# )

X = tf.placeholder(tf.float32, [None, 784])

X_img = tf.reshape(X, [-1, 28, 28, 1])

L1 = conv2d(X_img, 32, [3, 3])

print('L1:', L1)

L1: Tensor("Conv/Relu:0", shape=(?, 28, 28, 32), dtype=float32)


In [3]:
# https://www.tensorflow.org/api_docs/python/tf/contrib/layers/max_pool2d
# tf.contrib.layers.max_pool2d(
#     inputs,
#     kernel_size,
#     stride=2,
#     padding='VALID',
#     data_format=DATA_FORMAT_NHWC,
#     outputs_collections=None,
#     scope=None
# )

X = tf.placeholder(tf.float32, [None, 784])

X_img = tf.reshape(X, [-1, 28, 28, 1])

L1 = conv2d(X_img, 32, [3, 3])
print('L1:', L1)

L1 = max_pool2d(L1, [2, 2], padding='SAME')
print('L1:', L1)

L1: Tensor("Conv_1/Relu:0", shape=(?, 28, 28, 32), dtype=float32)
L1: Tensor("MaxPool2D/MaxPool:0", shape=(?, 14, 14, 32), dtype=float32)


In [4]:
# https://www.tensorflow.org/api_docs/python/tf/contrib/layers/dropout
# tf.contrib.layers.dropout(
#     inputs,
#     keep_prob=0.5,
#     noise_shape=None,
#     is_training=True,
#     outputs_collections=None,
#     scope=None
# )

keep = 0.75

X = tf.placeholder(tf.float32, [None, 784])
is_training = tf.placeholder_with_default(False, [])

X_img = tf.reshape(X, [-1, 28, 28, 1])

L1 = conv2d(X_img, 32, [3, 3])
print('L1:', L1)

L1 = max_pool2d(L1, [2, 2], padding='SAME')
print('L1:', L1)

L1 = dropout(L1, keep, is_training=is_training)
print('L1:', L1)

L1: Tensor("Conv_2/Relu:0", shape=(?, 28, 28, 32), dtype=float32)
L1: Tensor("MaxPool2D_1/MaxPool:0", shape=(?, 14, 14, 32), dtype=float32)
L1: Tensor("Dropout/cond/Merge:0", shape=(?, 14, 14, 32), dtype=float32)


In [5]:
keep = 0.75

X = tf.placeholder(tf.float32, [None, 784])
is_training = tf.placeholder_with_default(False, [])

X_img = tf.reshape(X, [-1, 28, 28, 1])

L1 = dropout(max_pool2d(conv2d(X_img, 32, [3, 3]), [2, 2], padding='SAME'), keep, is_training=is_training)
print('L1:', L1)

L1: Tensor("Dropout_1/cond/Merge:0", shape=(?, 14, 14, 32), dtype=float32)


In [6]:
keep = 0.75

X = tf.placeholder(tf.float32, [None, 784])
is_training = tf.placeholder_with_default(False, [])

X_img = tf.reshape(X, [-1, 28, 28, 1])

L1 = dropout(max_pool2d(conv2d(X_img, 32, [3, 3]), [2, 2], padding='SAME'), keep, is_training=is_training)
print('L1:', L1)

L2 = dropout(max_pool2d(conv2d(L1, 64, [3, 3]), [2, 2], padding='SAME'), keep, is_training=is_training)
print('L2:', L2)

L3 = dropout(max_pool2d(conv2d(L2, 128, [3, 3]), [2, 2], padding='SAME'), keep, is_training=is_training)
print('L3:', L3)

L1: Tensor("Dropout_2/cond/Merge:0", shape=(?, 14, 14, 32), dtype=float32)
L2: Tensor("Dropout_3/cond/Merge:0", shape=(?, 7, 7, 64), dtype=float32)
L3: Tensor("Dropout_4/cond/Merge:0", shape=(?, 4, 4, 128), dtype=float32)


In [7]:
keep = 0.75

X = tf.placeholder(tf.float32, [None, 784])
is_training = tf.placeholder_with_default(False, [])

X_img = tf.reshape(X, [-1, 28, 28, 1])

L1 = dropout(max_pool2d(conv2d(X_img, 32, [3, 3]), [2, 2], padding='SAME'), keep, is_training=is_training)
print('L1:', L1)

L2 = dropout(max_pool2d(conv2d(L1, 64, [3, 3]), [2, 2], padding='SAME'), keep, is_training=is_training)
print('L2:', L2)

L3 = dropout(max_pool2d(conv2d(L2, 128, [3, 3]), [2, 2], padding='SAME'), keep, is_training=is_training)
print('L3:', L3)

L3 = tf.reshape(L3, [-1, 4*4*128])
print('L3:', L3)

L1: Tensor("Dropout_5/cond/Merge:0", shape=(?, 14, 14, 32), dtype=float32)
L2: Tensor("Dropout_6/cond/Merge:0", shape=(?, 7, 7, 64), dtype=float32)
L3: Tensor("Dropout_7/cond/Merge:0", shape=(?, 4, 4, 128), dtype=float32)
L3: Tensor("Reshape_6:0", shape=(?, 2048), dtype=float32)


In [8]:
# https://www.tensorflow.org/api_docs/python/tf/contrib/layers/fully_connected
# tf.contrib.layers.fully_connected(
#     inputs,
#     num_outputs,
#     activation_fn=tf.nn.relu,
#     normalizer_fn=None,
#     normalizer_params=None,
#     weights_initializer=initializers.xavier_initializer(),
#     weights_regularizer=None,
#     biases_initializer=tf.zeros_initializer(),
#     biases_regularizer=None,
#     reuse=None,
#     variables_collections=None,
#     outputs_collections=None,
#     trainable=True,
#     scope=None
# )

keep = 0.75

X = tf.placeholder(tf.float32, [None, 784])
is_training = tf.placeholder_with_default(False, [])

X_img = tf.reshape(X, [-1, 28, 28, 1])

L1 = dropout(max_pool2d(conv2d(X_img, 32, [3, 3]), [2, 2], padding='SAME'), keep, is_training=is_training)
print('L1:', L1)

L2 = dropout(max_pool2d(conv2d(L1, 64, [3, 3]), [2, 2], padding='SAME'), keep, is_training=is_training)
print('L2:', L2)

L3 = dropout(max_pool2d(conv2d(L2, 128, [3, 3]), [2, 2], padding='SAME'), keep, is_training=is_training)
print('L3:', L3)

L3 = tf.reshape(L3, [-1, 4*4*128])
print('L3:', L3)

L4 = dropout(fully_connected(L3, 512), keep, is_training=is_training)
print('L4:', L4)

logits = fully_connected(L4, 10, activation_fn=None)
print('L5:', logits)

L1: Tensor("Dropout_8/cond/Merge:0", shape=(?, 14, 14, 32), dtype=float32)
L2: Tensor("Dropout_9/cond/Merge:0", shape=(?, 7, 7, 64), dtype=float32)
L3: Tensor("Dropout_10/cond/Merge:0", shape=(?, 4, 4, 128), dtype=float32)
L3: Tensor("Reshape_8:0", shape=(?, 2048), dtype=float32)
L4: Tensor("Dropout_11/cond/Merge:0", shape=(?, 512), dtype=float32)
L5: Tensor("fully_connected_1/BiasAdd:0", shape=(?, 10), dtype=float32)


In [9]:
keep = 0.75

X = tf.placeholder(tf.float32, [None, 784])
Y = tf.placeholder(tf.float32, [None, 10])
is_training = tf.placeholder_with_default(False, [])

X_img = tf.reshape(X, [-1, 28, 28, 1])

L1 = dropout(max_pool2d(conv2d(X_img, 32, [3, 3]), [2, 2], padding='SAME'), keep, is_training=is_training)

L2 = dropout(max_pool2d(conv2d(L1, 64, [3, 3]), [2, 2], padding='SAME'), keep, is_training=is_training)

L3 = dropout(max_pool2d(conv2d(L2, 128, [3, 3]), [2, 2], padding='SAME'), keep, is_training=is_training)
L3 = tf.reshape(L3, [-1, 4*4*128])

L4 = dropout(fully_connected(L3, 512), keep, is_training=is_training)

logits = fully_connected(L4, 10, activation_fn=None)

prediction = tf.argmax(logits, 1)
accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, tf.argmax(Y, 1)), tf.float32))

In [10]:
sess.run(tf.global_variables_initializer())

x_batch = mnist.train.images[:10]
y_batch = mnist.train.labels[:10]

print(logits.eval({X: x_batch}))
print(prediction.eval({X: x_batch}))
print(accuracy.eval({X: x_batch, Y: y_batch}))

[[ 0.045  0.11   0.029 -0.042 -0.095 -0.038 -0.015  0.138 -0.096 -0.009]
 [ 0.07   0.085  0.02   0.02  -0.091 -0.107 -0.024  0.169 -0.097  0.007]
 [ 0.043  0.083 -0.001 -0.014 -0.073 -0.05   0.012  0.114 -0.051 -0.007]
 [ 0.014  0.084  0.033  0.025 -0.022 -0.065 -0.01   0.138 -0.066  0.013]
 [ 0.016  0.027  0.04   0.015 -0.031 -0.043  0.02   0.106 -0.062  0.008]
 [ 0.06   0.069  0.033  0.016 -0.063 -0.073 -0.012  0.172 -0.115 -0.   ]
 [ 0.037  0.031  0.045  0.018 -0.053 -0.04   0.023  0.115 -0.062 -0.009]
 [ 0.072  0.111  0.012 -0.026 -0.066 -0.063 -0.017  0.158 -0.097 -0.047]
 [ 0.036  0.058 -0.006 -0.015 -0.059 -0.076  0.013  0.13  -0.051 -0.01 ]
 [ 0.064  0.088  0.012  0.018 -0.048 -0.062 -0.025  0.177 -0.105  0.016]]
[7 7 7 7 7 7 7 7 7 7]
0.1
