In [1]:
import tensorflow as tf

sess = tf.InteractiveSession()

In [2]:
logits = tf.constant([[1],
                      [-2],
                      [3],
                      [-2],
                      [4]], tf.float32)
H = 1 / (1 + tf.exp(-logits))
print(H.eval())

[[ 0.7310586 ]
 [ 0.11920292]
 [ 0.95257413]
 [ 0.11920292]
 [ 0.98201376]]


In [3]:
logits = tf.constant([[1],
                      [-2],
                      [3],
                      [-2],
                      [4]], tf.float32)
H = 1 / (1 + tf.exp(-logits))

is_positive = H > 0.5
print(is_positive.eval())

[[ True]
 [False]
 [ True]
 [False]
 [ True]]


In [4]:
logits = tf.constant([[1],
                      [-2],
                      [3],
                      [-2],
                      [4]], tf.float32)
H = 1 / (1 + tf.exp(-logits))

prediction = tf.cast(H > 0.5, tf.float32)
print(prediction.eval())

[[ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]]


In [5]:
logits = tf.constant([[1],
                      [-2],
                      [3],
                      [-2],
                      [4]], tf.float32)
H = 1 / (1 + tf.exp(-logits))
prediction = tf.cast(H > 0.5, tf.float32)
Y = tf.constant([[1],
                 [1],
                 [1],
                 [0],
                 [0]], tf.float32)

print(tf.equal(prediction, Y).eval(), '\n')
print(tf.cast(tf.equal(prediction, Y), tf.float32).eval(), '\n')

[[ True]
 [False]
 [ True]
 [ True]
 [False]] 

[[ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]] 



In [6]:
logits = tf.constant([[1],
                      [-2],
                      [3],
                      [-2],
                      [4]], tf.float32)
H = 1 / (1 + tf.exp(-logits))
prediction = tf.cast(H > 0.5, tf.float32)

Y = tf.constant([[1],
                 [1],
                 [1],
                 [0],
                 [0]], tf.float32)

accuracy = tf.reduce_mean(tf.cast(tf.equal(prediction, Y), tf.float32))
print(prediction.eval(), '\n')
print(accuracy.eval())

[[ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]] 

0.6


In [7]:
logits = tf.constant([[1],
                      [-2],
                      [3],
                      [-2],
                      [4]], tf.float32)
H = 1 / (1 + tf.exp(-logits))
Y = tf.constant([[1],
                 [1],
                 [1],
                 [0],
                 [0]], tf.float32)
print(H.eval(), '\n')

c = Y * -tf.log(H)
print(-tf.log(H).eval(), '\n')
print(c.eval())

[[ 0.7310586 ]
 [ 0.11920292]
 [ 0.95257413]
 [ 0.11920292]
 [ 0.98201376]] 

[[ 0.31326166]
 [ 2.12692809]
 [ 0.04858734]
 [ 2.12692809]
 [ 0.01814996]] 

[[ 0.31326166]
 [ 2.12692809]
 [ 0.04858734]
 [ 0.        ]
 [ 0.        ]]


In [8]:
logits = tf.constant([[1],
                      [-2],
                      [3],
                      [-2],
                      [4]], tf.float32)
H = 1 / (1 + tf.exp(-logits))
Y = tf.constant([[1],
                 [1],
                 [1],
                 [0],
                 [0]], tf.float32)
print(H.eval(), '\n')

c = (1 - Y) * -tf.log(1 - H)
print((-tf.log(1-H)).eval(), '\n')
print(c.eval())

[[ 0.7310586 ]
 [ 0.11920292]
 [ 0.95257413]
 [ 0.11920292]
 [ 0.98201376]] 

[[ 1.31326175]
 [ 0.126928  ]
 [ 3.04858756]
 [ 0.126928  ]
 [ 4.01814842]] 

[[ 0.        ]
 [ 0.        ]
 [ 0.        ]
 [ 0.126928  ]
 [ 4.01814842]]


In [9]:
logits = tf.constant([[1],
                      [-2],
                      [3],
                      [-2],
                      [4]], tf.float32)
H = 1 / (1 + tf.exp(-logits))
Y = tf.constant([[1],
                 [1],
                 [1],
                 [0],
                 [0]], tf.float32)
print(H.eval(), '\n')

c = -(Y*tf.log(H) + (1-Y)*tf.log(1-H))
print(c.eval())

[[ 0.7310586 ]
 [ 0.11920292]
 [ 0.95257413]
 [ 0.11920292]
 [ 0.98201376]] 

[[ 0.31326166]
 [ 2.12692809]
 [ 0.04858734]
 [ 0.126928  ]
 [ 4.01814842]]


In [10]:
logits = tf.constant([[1],
                      [-2],
                      [3],
                      [-2],
                      [4]], tf.float32)
H = 1 / (1 + tf.exp(-logits))
Y = tf.constant([[1],
                 [1],
                 [1],
                 [0],
                 [0]], tf.float32)
print(H.eval(), '\n')

cost = -tf.reduce_mean(Y*tf.log(H) + (1-Y)*tf.log(1-H))
print(cost.eval())

[[ 0.7310586 ]
 [ 0.11920292]
 [ 0.95257413]
 [ 0.11920292]
 [ 0.98201376]] 

1.32677


In [11]:
logits = tf.constant([[10],
                      [10],
                      [10],
                      [-10],
                      [-10]], tf.float32)
H = 1 / (1 + tf.exp(-logits))
Y = tf.constant([[1],
                 [1],
                 [1],
                 [0],
                 [0]], tf.float32)

cost = -tf.reduce_mean(Y*tf.log(H) + (1-Y)*tf.log(1-H))
print(H.eval(), '\n')
print(cost.eval())

[[  9.99954581e-01]
 [  9.99954581e-01]
 [  9.99954581e-01]
 [  4.53978719e-05]
 [  4.53978719e-05]] 

4.54198e-05
