In [1]:
import tensorflow as tf

sess = tf.InteractiveSession()

In [2]:
a = tf.placeholder(tf.float32, [])
b = tf.placeholder(tf.float32, [])
add = a + b
print(add.eval({a: 1, b: 2}))

3.0


In [3]:
# https://www.tensorflow.org/api_docs/python/tf/placeholder_with_default
# tf.placeholder_with_default(
#     input,
#     shape,
#     name=None
# )

a = tf.placeholder_with_default(1., [])
b = tf.placeholder_with_default(2., [])
add = a + b

print(add.eval())
print(add.eval({a: 10, b: 20}))

3.0
30.0


In [4]:
print(a)

a = tf.placeholder_with_default(tf.constant(1., tf.float64), [])

print(a)

Tensor("PlaceholderWithDefault:0", shape=(), dtype=float32)
Tensor("PlaceholderWithDefault_2:0", shape=(), dtype=float64)


In [5]:
P = tf.constant([[0],[0],[1],[1],[1],[1],[0],[0],[0],[0]])
Y = tf.constant([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])

print(P.eval())

[[0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]]


In [6]:
P = tf.constant([[0],[0],[1],[1],[1],[1],[0],[0],[0],[0]])
Y = tf.constant([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])

print(tf.concat([P, Y], 1).eval())

[[0 1]
 [0 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [7]:
# true positive
P = tf.constant([[0],[0],[1],[1],[1],[1],[0],[0],[0],[0]])
Y = tf.constant([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])

print(tf.concat([P, Y, P*Y], 1).eval())

tp = tf.count_nonzero(P * Y)
print('true positive:', tp.eval())

[[0 1 0]
 [0 1 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
true positive: 3


In [8]:
# true negative
P = tf.constant([[0],[0],[1],[1],[1],[1],[0],[0],[0],[0]])
Y = tf.constant([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])

print(tf.concat([P, Y, P-1, Y-1, (P-1)*(Y-1)], 1).eval())

tn = tf.count_nonzero((P - 1) * (Y - 1))
print('true negative:', tn.eval())

[[ 0  1 -1  0  0]
 [ 0  1 -1  0  0]
 [ 1  1  0  0  0]
 [ 1  1  0  0  0]
 [ 1  1  0  0  0]
 [ 1  0  0 -1  0]
 [ 0  0 -1 -1  1]
 [ 0  0 -1 -1  1]
 [ 0  0 -1 -1  1]
 [ 0  0 -1 -1  1]]
true negative: 4


In [9]:
# false positive
P = tf.constant([[0],[0],[1],[1],[1],[1],[0],[0],[0],[0]])
Y = tf.constant([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])

print(tf.concat([P, Y, P, Y-1, P*(Y-1)], 1).eval())

fp = tf.count_nonzero(P * (Y-1))
print('false positive:', fp.eval())

[[ 0  1  0  0  0]
 [ 0  1  0  0  0]
 [ 1  1  1  0  0]
 [ 1  1  1  0  0]
 [ 1  1  1  0  0]
 [ 1  0  1 -1 -1]
 [ 0  0  0 -1  0]
 [ 0  0  0 -1  0]
 [ 0  0  0 -1  0]
 [ 0  0  0 -1  0]]
false positive: 1


In [10]:
# false negative
P = tf.constant([[0],[0],[1],[1],[1],[1],[0],[0],[0],[0]])
Y = tf.constant([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])

print(tf.concat([P, Y, P-1, Y, (P-1)*Y], 1).eval())

fn = tf.count_nonzero((P - 1) * Y)
print('false negative:', fn.eval())

[[ 0  1 -1  1 -1]
 [ 0  1 -1  1 -1]
 [ 1  1  0  1  0]
 [ 1  1  0  1  0]
 [ 1  1  0  1  0]
 [ 1  0  0  0  0]
 [ 0  0 -1  0  0]
 [ 0  0 -1  0  0]
 [ 0  0 -1  0  0]
 [ 0  0 -1  0  0]]
false negative: 2


In [11]:
P = tf.constant([[0],[0],[1],[1],[1],[1],[0],[0],[0],[0]])
Y = tf.constant([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])

tp = tf.count_nonzero(P * Y)
tn = tf.count_nonzero((P - 1) * (Y - 1))
fp = tf.count_nonzero(P * (Y-1))
fn = tf.count_nonzero((P - 1) * Y)

print('true positive:', tp.eval())
print('true negative:', tn.eval())
print('false positive:', fp.eval())
print('false negative:', fn.eval())

true positive: 3
true negative: 4
false positive: 1
false negative: 2


In [12]:
P = tf.constant([[0],[0],[1],[1],[1],[1],[0],[0],[0],[0]])
Y = tf.constant([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])

print('true positive:', tp.eval())
print('true negative:', tn.eval())
print('false positive:', fp.eval())
print('false negative:', fn.eval())

accuracy = tf.reduce_mean(tf.cast(tf.equal(P, Y), tf.float32))
print('accuracy:', accuracy.eval())

accuracy = (tp + tn) / (tp + tn + fp + fn)
print('accuracy:', accuracy.eval())

true positive: 3
true negative: 4
false positive: 1
false negative: 2
accuracy: 0.7
accuracy: 0.7


In [13]:
P = tf.constant([[0],[0],[1],[1],[1],[1],[0],[0],[0],[0]])
Y = tf.constant([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])

print('true positive:', tp.eval())
print('true negative:', tn.eval())
print('false positive:', fp.eval())
print('false negative:', fn.eval())

precision = tp / (tp + fp)
print('precision:', precision.eval())

true positive: 3
true negative: 4
false positive: 1
false negative: 2
precision: 0.75


In [14]:
P = tf.constant([[0],[0],[1],[1],[1],[1],[0],[0],[0],[0]])
Y = tf.constant([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])

print('true positive:', tp.eval())
print('true negative:', tn.eval())
print('false positive:', fp.eval())
print('false negative:', fn.eval())

recall = tp / (tp + fn)
print('recall:', recall.eval())

true positive: 3
true negative: 4
false positive: 1
false negative: 2
recall: 0.6


In [15]:
P = tf.constant([[0],[0],[1],[1],[1],[1],[0],[0],[0],[0]])
Y = tf.constant([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])

print('true positive:', tp.eval())
print('true negative:', tn.eval())
print('false positive:', fp.eval())
print('false negative:', fn.eval())

f1 = 2 * precision * recall / (precision + recall)
print('f1:', f1.eval())

true positive: 3
true negative: 4
false positive: 1
false negative: 2
f1: 0.666666666667


In [16]:
P = tf.constant([[0],[0],[1],[1],[1],[1],[0],[0],[0],[0]])
Y = tf.constant([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])

tp = tf.count_nonzero(P * Y)
tn = tf.count_nonzero((P - 1) * (Y - 1))
fp = tf.count_nonzero(P * (Y-1))
fn = tf.count_nonzero((P - 1) * Y)

accuracy = (tp + tn) / (tp + tn + fp + fn)
precision = tp / (tp + fp)
recall = tp / (tp + fn)
f1 = 2 * precision * recall / (precision + recall)

print('accuracy:', accuracy.eval())
print('precision:', precision.eval())
print('recall:', recall.eval())
print('f1:', f1.eval())

accuracy: 0.7
precision: 0.75
recall: 0.6
f1: 0.666666666667


In [17]:
P = tf.constant([[1],[0],[0],[0],[0],[0],[0],[0],[0],[0]])
Y = tf.constant([[1],[1],[1],[1],[1],[0],[0],[0],[0],[0]])

tp = tf.count_nonzero(P * Y)
tn = tf.count_nonzero((P - 1) * (Y - 1))
fp = tf.count_nonzero(P * (Y-1))
fn = tf.count_nonzero((P - 1) * Y)

accuracy = (tp + tn) / (tp + tn + fp + fn)
precision = tp / (tp + fp)
recall = tp / (tp + fn)
mean = (precision + recall) / 2
f1 = 2 * precision * recall / (precision + recall)

print('accuracy:', accuracy.eval())
print('precision:', precision.eval())
print('recall:', recall.eval())
print('mean:', mean.eval())
print('f1:', f1.eval())

accuracy: 0.6
precision: 1.0
recall: 0.2
mean: 0.6
f1: 0.333333333333


In [18]:
P = tf.constant([[1],[1],[1],[1],[1],[1],[1],[1],[1],[1]])
Y = tf.constant([[1],[1],[1],[1],[0],[0],[0],[0],[0],[0]])

tp = tf.count_nonzero(P * Y)
tn = tf.count_nonzero((P - 1) * (Y - 1))
fp = tf.count_nonzero(P * (Y-1))
fn = tf.count_nonzero((P - 1) * Y)

accuracy = (tp + tn) / (tp + tn + fp + fn)
precision = tp / (tp + fp)
recall = tp / (tp + fn)
mean = (precision + recall) / 2
f1 = 2 * precision * recall / (precision + recall)

print('accuracy:', accuracy.eval())
print('precision:', precision.eval())
print('recall:', recall.eval())
print('mean:', mean.eval())
print('f1:', f1.eval())

accuracy: 0.4
precision: 0.4
recall: 1.0
mean: 0.7
f1: 0.571428571429
