In [1]:
import tensorflow as tf
import numpy as np

sess = tf.InteractiveSession()

In [2]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a)
print(a.shape)
print(a.dtype)

[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [  9.  10.  11.  12.]
 [ 13.  14.  15.  16.]
 [ 17.  18.  19.  20.]]
(5, 4)
float32


In [3]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[0])

[ 1.  2.  3.  4.]


In [4]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[2])

[  9.  10.  11.  12.]


In [5]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[-1])

[ 17.  18.  19.  20.]


In [6]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[1, 1])

6.0


In [7]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[3, -1])

16.0


In [8]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[1:3])

[[  5.   6.   7.   8.]
 [  9.  10.  11.  12.]]


In [9]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[1:])

[[  5.   6.   7.   8.]
 [  9.  10.  11.  12.]
 [ 13.  14.  15.  16.]
 [ 17.  18.  19.  20.]]


In [10]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[0::2])

[[  1.   2.   3.   4.]
 [  9.  10.  11.  12.]
 [ 17.  18.  19.  20.]]


In [11]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[::-1])

[[ 17.  18.  19.  20.]
 [ 13.  14.  15.  16.]
 [  9.  10.  11.  12.]
 [  5.   6.   7.   8.]
 [  1.   2.   3.   4.]]


In [12]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[[0]])

[[ 1.  2.  3.  4.]]


In [13]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[[0, 1, 3]])

[[  1.   2.   3.   4.]
 [  5.   6.   7.   8.]
 [ 13.  14.  15.  16.]]


In [14]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[:, 0:3])

[[  1.   2.   3.]
 [  5.   6.   7.]
 [  9.  10.  11.]
 [ 13.  14.  15.]
 [ 17.  18.  19.]]


In [15]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[0:2, 0:2])

[[ 1.  2.]
 [ 5.  6.]]


In [16]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[:, 0:-1])

[[  1.   2.   3.]
 [  5.   6.   7.]
 [  9.  10.  11.]
 [ 13.  14.  15.]
 [ 17.  18.  19.]]


In [17]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[:, -1:])

[[  4.]
 [  8.]
 [ 12.]
 [ 16.]
 [ 20.]]


In [18]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]], np.float32)
print(a[:, [-1]])

[[  4.]
 [  8.]
 [ 12.]
 [ 16.]
 [ 20.]]


In [19]:
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html
# numpy.loadtxt(fname,
#               dtype=<type 'float'>,
#               comments='#',
#               delimiter=None,
#               converters=None,
#               skiprows=0,
#               usecols=None,
#               unpack=False, ndmin=0)

xy = np.loadtxt('../../dataset/01-test_score.csv', delimiter=',')
print(xy.shape)
print(xy.dtype)

(25, 4)
float64


In [20]:
xy = np.loadtxt('../../dataset/01-test_score.csv', dtype=np.float32, delimiter=',')
print(xy)
print(xy.shape)
print(xy.dtype)

[[  73.   80.   75.  152.]
 [  93.   88.   93.  185.]
 [  89.   91.   90.  180.]
 [  96.   98.  100.  196.]
 [  73.   66.   70.  142.]
 [  53.   46.   55.  101.]
 [  69.   74.   77.  149.]
 [  47.   56.   60.  115.]
 [  87.   79.   90.  175.]
 [  79.   70.   88.  164.]
 [  69.   70.   73.  141.]
 [  70.   65.   74.  141.]
 [  93.   95.   91.  184.]
 [  79.   80.   73.  152.]
 [  70.   73.   78.  148.]
 [  93.   89.   96.  192.]
 [  78.   75.   68.  147.]
 [  81.   90.   93.  183.]
 [  88.   92.   86.  177.]
 [  78.   83.   77.  159.]
 [  82.   86.   90.  177.]
 [  86.   82.   89.  175.]
 [  78.   83.   85.  175.]
 [  76.   83.   71.  149.]
 [  96.   93.   95.  192.]]
(25, 4)
float32


In [21]:
x_data = xy[:, 0:-1]
print(x_data)
print(x_data.shape)

[[  73.   80.   75.]
 [  93.   88.   93.]
 [  89.   91.   90.]
 [  96.   98.  100.]
 [  73.   66.   70.]
 [  53.   46.   55.]
 [  69.   74.   77.]
 [  47.   56.   60.]
 [  87.   79.   90.]
 [  79.   70.   88.]
 [  69.   70.   73.]
 [  70.   65.   74.]
 [  93.   95.   91.]
 [  79.   80.   73.]
 [  70.   73.   78.]
 [  93.   89.   96.]
 [  78.   75.   68.]
 [  81.   90.   93.]
 [  88.   92.   86.]
 [  78.   83.   77.]
 [  82.   86.   90.]
 [  86.   82.   89.]
 [  78.   83.   85.]
 [  76.   83.   71.]
 [  96.   93.   95.]]
(25, 3)


In [22]:
y_data = xy[:, [-1]]
print(y_data)
print(y_data.shape)

[[ 152.]
 [ 185.]
 [ 180.]
 [ 196.]
 [ 142.]
 [ 101.]
 [ 149.]
 [ 115.]
 [ 175.]
 [ 164.]
 [ 141.]
 [ 141.]
 [ 184.]
 [ 152.]
 [ 148.]
 [ 192.]
 [ 147.]
 [ 183.]
 [ 177.]
 [ 159.]
 [ 177.]
 [ 175.]
 [ 175.]
 [ 149.]
 [ 192.]]
(25, 1)


In [23]:
y_data = xy[:, -1:]
print(y_data.shape)

(25, 1)


In [24]:
num_features = xy.shape[1] - 1
print(num_features)

3


In [25]:
Y = tf.constant([[1],
                 [2],
                 [3],
                 [4],
                 [5]])
H1 = tf.constant([[1],
                  [2],
                  [3],
                  [4],
                  [5]])
H2 = tf.constant([[0],
                  [0],
                  [0],
                  [0],
                  [0]])
print((H1 - Y).eval())
print((H2 - Y).eval())

[[0]
 [0]
 [0]
 [0]
 [0]]
[[-1]
 [-2]
 [-3]
 [-4]
 [-5]]


In [26]:
# https://www.tensorflow.org/api_docs/python/tf/abs
# tf.abs(x, name=None)

print(tf.abs(H1 - Y).eval())
print(tf.abs(H2 - Y).eval())

[[0]
 [0]
 [0]
 [0]
 [0]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [27]:
print(tf.reduce_mean(tf.abs(H1 - Y)).eval())
print(tf.reduce_mean(tf.abs(H2 - Y)).eval())

0
3
