In [32]:
import tensorflow as tf

sess = tf.InteractiveSession()

In [33]:
logits = tf.constant(([[10],
                       [-1000],
                       [10],
                       [8],
                       [-20]]), tf.float32)
Y = tf.constant(([[1],
                  [1],
                  [1],
                  [1],
                  [1]]), tf.float32)
H = 1 / (1 + tf.exp(-logits))
print(H.eval())

[[  9.99954581e-01]
 [  0.00000000e+00]
 [  9.99954581e-01]
 [  9.99664664e-01]
 [  2.06115369e-09]]


In [34]:
H = tf.sigmoid(logits)
print(H.eval())

[[  9.99954581e-01]
 [  0.00000000e+00]
 [  9.99954581e-01]
 [  9.99664664e-01]
 [  2.06115369e-09]]


In [35]:
logits = tf.constant(([[10],
                       [-1000],
                       [10],
                       [8],
                       [-20]]), tf.float32)
Y = tf.constant(([[1],
                  [1],
                  [1],
                  [1],
                  [1]]), tf.float32)
H = 1 / (1 + tf.exp(-logits))

cost_unit = -(Y * tf.log(H) + (1-Y) * tf.log(1-H))
cost = -tf.reduce_mean(Y * tf.log(H) + (1-Y) * tf.log(1-H))
print(cost_unit.eval(), '\n')
print(cost.eval())

[[  4.54197725e-05]
 [             inf]
 [  4.54197725e-05]
 [  3.35391960e-04]
 [  2.00000000e+01]] 

inf


In [25]:
cost_unit = tf.nn.sigmoid_cross_entropy_with_logits(labels=Y, logits=logits)
print(cost_unit.eval())

[[  4.53988978e-05]
 [  1.00000000e+03]
 [  4.53988978e-05]
 [  3.35406367e-04]
 [  2.00000000e+01]]


In [26]:
cost = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(labels=Y, logits=logits))
print(cost.eval())

204.0
